FROM cuda_ros_docker

SHELL ["/bin/bash", "-c"]

RUN apt-get update \
    && python3 -m pip install open3d

RUN python3 -m pip install jax==0.2.20 jaxlib==0.3.2+cuda11.cudnn82 -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html

# RUN python3 -m pip install --no-cache-dir --no-cache-dir networkx==3.1
RUN python3 -m pip install networkx==3.1 

RUN python3 -m pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118

RUN python3 -m pip install hydra-core 
RUN python3 -m pip install accelerate

RUN rm -rf /var/lib/apt/lists/*

ENTRYPOINT ["/ros_entrypoint.sh"]
CMD ["bash"]