set(turtlebot_calibration_MESSAGE_FILES "/home/soumoroy/crowdsurfer_new_implementation_ws/crowdsurfer-ros1/src/turtlebot2_noetic_packages/turtlebot_apps/turtlebot_calibration/msg/ScanAngle.msg")
set(turtlebot_calibration_SERVICE_FILES "")
